language: generic
services:
  - docker
install:
  # On 1. day, still use last month's tarfile,
  # the latest one may not be on the mirror yet
  - ./download yesterday
script:
  - ./build
  - ./tag
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'
