language: generic
sudo: required
services:
  - docker
install:
  - sudo pip install https://github.com/goldmann/docker-squash/archive/master.zip
  # Force the 2.x release of docker, as docker-squash is currently incompatible (2018-02-05)
  - sudo pip install "docker<3.0.0"
  # On 1. day, still use last month's tarfile,
  # the latest one may not be on the mirror yet
  - export TAR_DATE=$(date --date=yesterday +'%Y.%m.01')
  - sudo mkdir -p /root/.gnupg
  - echo no-greeting                              | sudo tee -a /root/.gnupg/gpg.conf
  - echo keyserver hkp://pool.sks-keyservers.net  | sudo tee -a /root/.gnupg/gpg.conf
  - echo keyserver-options timeout=10             | sudo tee -a /root/.gnupg/gpg.conf
script:
  - ./pull || sudo -H ./build
  - ./update
after_success:
  - '[ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./push'
